<?php

/**
 * @file
 * Statistics for OpenScholar Single Access Point (OSSAP).
 */

/**
 * Defines the settings variable name for the total child sites count block.
 */
define('OSSAP_SITES_BLOCK_SETTINGS', 'ossap_stats_sites_settings');
define('OSSAP_STATS_EMBED_MESSAGE_COUNT_DEFAULT', 3);
/**
 * Implements hook_menu().
 */
function ossap_stats_menu() {
  $items = array();

  $items['ossap/stats'] = array(
    'title' => t('OpenScholar SAP stats'),
    'page callback' => '_ossap_stats_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['ossap/stats.js'] = array(
    'title' => t('OpenScholar Stats'),
    'page callback' => '_ossap_stats_embed_js',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  //osboard menu start
  $items['ossap/most-viewed-pages'] = array(
    'title' => t('OpenScholar Board - Most Viewed Pages'),
    'type' => MENU_CALLBACK,
    'page callback' => 'ossap_stats_viewed_pages',
    'access callback' => TRUE,
  );
  
  $items['ossap/most-visited-sites'] = array(
    'title' => t('OpenScholar Board - Most visited Sites'),
    'type' => MENU_CALLBACK,
    'page callback' => 'ossap_stats_visited_sites',
    'access callback' => TRUE,
  );
  
   $items['admin/config/ossap_os_board'] = array(
    'title' => 'OSSA - OpenScholar Board Settings',
    'description' => 'Administer OpenScholar Board specific settings.',
    'position' => 'left',
    'weight' => -5,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ossap_stats_settings_form'),
    'access arguments' => array('administer content'),
  );
  //osboard menu start
  return $items;
}

/*
* ossap_stats_settings_form
* parameters : form_state
* creates an admin form for os_board for admins to
* enter the data for activating Google Analytics 
*/
function ossap_stats_settings_form($form_state){
 $form = array();

 $form['ossap_stats_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Enter OS Stats setting details here'),
    '#weight' => 0,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['ossap_stats_settings']['ossap_stats_private_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Private Key'),
    '#default_value' => variable_get('ossap_stats_private_key',""),
    '#description' => t('Add Private Key here'),
  );
  
  $form['ossap_stats_settings']['ossap_stats_private_key_fid'] = array(
    '#type' => 'managed_file',
    '#title' => t('Private Key file'),
	'#required' => TRUE,
    '#description' => t('Upload the Private Key file from Google and type service Account'),
    '#default_value' => variable_get('ossap_stats_private_key_fid', ''),
    '#upload_validators' => array(
       'file_validate_extensions' => array('p12'),
       'file_validate_size' => array(2*1024*1024),
        ),
      );
  
  $form['ossap_stats_settings']['ossap_stats_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Client Id'),
	'#required' => TRUE,
    '#default_value' => variable_get('ossap_stats_client_id',""),
    '#description' => t('Add Client Id here'),
  );

  $form['ossap_stats_settings']['ossap_stats_service_gmail'] = array(
    '#type' => 'textfield',
    '#title' => t('Service Gmail'),
    '#required' => TRUE,
    '#default_value' => variable_get('ossap_stats_service_gmail',""),
    '#description' => t('Add Service Account Gmail here'),
   );
   
   $form['ossap_stats_settings']['ossap_stats_analytics_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Analytics Id'),
    '#required' => TRUE,
    '#default_value' => variable_get('ossap_stats_analytics_id'),
    '#description' => t('Add Analytics Id here'),
   );

  return system_settings_form($form);

}

/*
* ossap_stats_load_includes
* include all the required files via module_load_include
*/
function ossap_stats_load_includes(){
    module_load_include('php', 'ossap_stats', 'libraries/src/Google_Client');
    module_load_include('php', 'ossap_stats', 'libraries/src/contrib/Google_AnalyticsService');
    module_load_include('inc', 'ossap_stats', 'ossap_stats_credentials');
}

/*
* ossap_stats_visited_sites()
* no parameters. returns most frequently visited sites
*/
 function ossap_stats_visited_sites(){
     //load the includes
	 ossap_stats_load_includes();
	 // portals list which should be avoided in the output
	 $portals = array('hwp.harvard.edu','projects.iq.harvard.edu','scholar.harvard.edu');
     //get results from the design_output function by sending the parameter of type = visits
     $results = ossap_stats_design_output('visits');

     //create the array of results
     foreach($results['rows'] as $result) {
	    if (!in_array($result[0], $portals)){
		$sites_rows[] = array($result[0],$result[1]);
		}
	}	 
     //return output as a json object;
     drupal_json_output($sites_rows);
 
 }

/*
* ossap_stats_viewed_pages()
* no parameters. returns most frequently viewed pages
*/
function ossap_stats_viewed_pages(){
     //load the includes
	 ossap_stats_load_includes();
     //get results from the design_output function by sending the parameter of type = pageviews
     $results = ossap_stats_design_output('pageviews');
	 
     //create the array of results
     foreach($results['rows'] as $result) {
         if ($result[1] != '/') {
           $combined_page = $result[0].$result[1];
         } else {
             $combined_page = $result[0].'/home';
         }
         $pages_rows[] = array($combined_page,$result[2]);
     }
	 
     //return output as a json object;
     drupal_json_output($pages_rows);
 }

/**
 * Implements hook_theme().
 */
function ossap_stats_theme() {
  return array(
    'ossap_stats_embed_js' => array(
      'variables' => array(
        'aggregates' => NULL,
        'os_version' => NULL,
        'messages' => NULL,
        'getsatisfaction' => NULL,
        'visited_sites' => NULL,
        'viewed_pages' => NULL
		
      ),
      'template' => 'ossap-stats-embed-js',
    ),
  );
}

/**
 * Page callback; exposes all OSSAP stats in one JSON object.
 */
function _ossap_stats_page() {
  // Prepares a safe version of the child_domains variable to expose.
  $child_domains = variable_get('ossap_child_domains', array());
  foreach ($child_domains as $url => $info) {
    if (isset($info['restuser'])) {
      unset($child_domains[$url]['restuser']);
    }
  }

  // Prepares the data array to render to the page as JSON.
  $data = array(
    'success' => TRUE,
    'child_domains' => $child_domains,
    'aggregates' => variable_get('ossap_stats_aggregates', array()),
    'os_version' => _ossap_stats_get_os_version(),
  );

  // Adds GetSatisfaction statistics if any statistics exist.
  $getsatisfaction = variable_get('ossap_stats_getsatisfaction', NULL);
  if ($getsatisfaction !== NULL) {
    $data['getsatisfaction'] = $getsatisfaction;
  }

  // Adds activity statistics if any statistics exist.
  $activity = variable_get('ossap_stats_activity', NULL);
  if ($activity !== NULL) {
    $data['activity'] = $activity;
  } 
  
  // Add most visited sites statistics if any statistics exist.
  $most_visited_sites = variable_get('visited_sites', NULL);
  if ($most_visited_sites !== NULL) {
    $data['visited_sites'] = $most_visited_sites;
  }
  
  // Add most viewed pages statistics if any statistics exist.
  $most_viewed_pages = variable_get('viewed_pages', NULL);
  if ($most_viewed_pages !== NULL) {
    $data['viewed_pages'] = $most_viewed_pages;
  }
   
   drupal_json_output($data);
}

/**
 * Page callback; formats and displays the embed code to paste on any site.
 */
function _ossap_stats_embed_js($stat) {
  drupal_add_http_header('Content-Type', 'text/javascript; charset=utf-8');
  $aggregates = variable_get('ossap_stats_aggregates', array());

  // Prepares any available GetSatisfaction statistics.
  $getsatisfaction = variable_get('ossap_stats_getsatisfaction', array());
  
  // Prepares any available Most visited statistics.
  $most_visited_sites = variable_get('visited_sites', array());
  
  // Prepares any available Most viewed statistics.
  $most_viewed_pages = variable_get('viewed_pages', array());
  
  // Prepares the activity messages.
  $messages = '';
  $activity = variable_get('ossap_stats_activity', array());
  if (isset($activity['messages']) && !empty($activity['messages'])) {
    $count = variable_get('ossap_stats_embed_message_count', OSSAP_STATS_EMBED_MESSAGE_COUNT_DEFAULT);
    $items = array_slice($activity['messages'], 0, $count);
    $build = array(
      '#theme' => 'item_list',
      '#items' => $items,
      '#attributes' => array('class' => array('ossap-stats-embed-messages')),
    );
    $messages = json_encode(drupal_render($build));
  }
  $variables = array(
    'aggregates' => $aggregates,
    'os_version' => _ossap_stats_get_os_version(),
    'messages' => $messages,
    'getsatisfaction' => $getsatisfaction,
    //added variables for most_visited_sites and most_viewed_pages
    'visited_sites' => $most_visited_sites,
    'viewed_pages' => $most_viewed_pages,
  );
   print theme('ossap_stats_embed_js', $variables);
   exit;
}

/**
 * Implements hook_cron_queue_info().
 */
function ossap_stats_cron_queue_info() {
  $queue = array();

  $queue['ossap_stats_queue'] = array(
    'worker callback' => 'ossap_stats_block_worker',
  );

  return $queue;
}

/**
 * Implements hook_cron().
 */
function ossap_stats_cron() {
  $queue = DrupalQueue::get('ossap_stats_queue');
  $queue->createQueue();
  // Add an array key as a new cron job key
  $stats = array('sites', 'getsatisfaction', 'activity', 'visited_sites', 'viewed_pages');
  foreach ($stats as $stat) {
    $queue->createItem($stat);
  }
}

/**
 * Cron worker callback for OSSAP stats.
 */
function ossap_stats_block_worker($stat = '') {
  switch ($stat) {
    case 'sites':
      ossap_stats_sites_cron_worker();
      break;
    case 'getsatisfaction':
      ossap_stats_getsatisfaction_cron_worker();
      break;
    case 'activity':
      ossap_stats_activity_cron_worker();
      break;
    // Add a case statement in the cron worker function
    case 'visited_sites':
      ossap_stats_most_visited_sites_cron_worker();
      break;
    case 'viewed_pages':
      ossap_stats_most_viewed_pages_cron_worker();
      break;
  }
}

// Add a cron worker callback function that calls the external function
function ossap_stats_most_visited_sites_cron_worker(){
  $function = 'ossap_stats_visited_sites';
  if (!function_exists($function)) {
    return;
  }
  
  $most_visited_sites_stats = $function();
  if (!empty($most_visited_sites_stats)) {
    variable_set('visited_sites', $most_visited_sites_stats);
  }
}

function ossap_stats_most_viewed_pages_cron_worker(){
  $function = 'ossap_stats_viewed_pages';
  if (!function_exists($function)) {
    return;
  }
  
  $most_viewed_pages_stats = $function();
  if (!empty($most_viewed_pages_stats)) {
    variable_set('viewed_pages', $most_viewed_pages_stats);
  }
}


function ossap_stats_getsatisfaction_cron_worker() {
  $function = 'getsatisfaction_integration_stats';
  if (!function_exists($function)) {
    return;
  }

  $getsatisfaction_stats = $function();
  if (!empty($getsatisfaction_stats)) {
    variable_set('ossap_stats_getsatisfaction', $getsatisfaction_stats);
  }
}

/**
 * Cron queue worker to aggregate latest status messages.
 */
function ossap_stats_activity_cron_worker() {
  $activity = array();

  $servers = variable_get('ossap_child_domains', array());
  $domains = array_keys($servers);
  $options = array();
  foreach ($domains as $domain) {
    $url = "http://$domain/activity.json";
    $result = drupal_http_request($url, $options);
    if (isset($result->data)) {
      $data = drupal_json_decode($result->data);
      foreach ($data['messages'] as $key => $info) {
        $time = _ossap_stats_time_markup($info['timestamp']);

        $activity['messages'][$key] = array(
          'data' => $time . $info['markup'],
        );
      }
    }
  }

  if (!empty($activity)) {
    if (!empty($activity['messages'])) {
      // Sorts the activity messages first by timestamp desc, then by nid desc.
      ksort($activity['messages'], SORT_NUMERIC);
      $activity['messages'] = array_reverse($activity['messages']);
    }
    variable_set('ossap_stats_activity', $activity);
  }
}

/**
 * Cron queue worker for the ossap_stats_sites block.
 *
 * Invokes drupal_http_request on each child server to get total sites stats.
 */
function ossap_stats_sites_cron_worker() {
  $aggregates = array();

  $stat_keys = array_keys(_os_stats_queries());
  $unsummable = array('filesize');
  $servers = variable_get('ossap_child_domains', array());
  $domains = array_keys($servers);
  $options = array();
  foreach ($domains as $domain) {
    $url = "http://$domain/stats";
    $result = drupal_http_request($url, $options);
    if (isset($result->data)) {
      $data = drupal_json_decode($result->data);
      foreach ($stat_keys as $stat) {
        if (in_array($stat, $unsummable)) {
          continue;
        }
        if (isset($data[$stat]['value'])) {
          if(!isset($aggregates[$stat])){
            $aggregates[$stat] = 0;
          }
          $aggregates[$stat] += $data[$stat]['value'];
        }
      }
    }
  }

  if (count($aggregates)) {
    variable_set('ossap_stats_aggregates', $aggregates);
  }
}

/**
 * Gets current OpenScholar release version string, like "3.10".
 */
function _ossap_stats_get_os_version() {
  // Parses the info file to get os_version.
  $info = system_get_info('module','openscholar');

  // Removes the Drupal major version number prefix (i.e. "7.x-").
  $os_version = substr($info['os_version'], 4);

  return $os_version;
}

/**
 * Implements hook_form_FORM_ID_alter() for os_settings_form.
 *
 * Allows admins to set the global Google Analytics ID and sitewide options.
 */
function ossap_stats_form_os_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['ossap_stats'] = array(
    '#type' => 'fieldset',
    '#title' => t('OSSAP Stats'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $prefix = '<h4>' . t('Embeddable stats') . '</h4><p class="description">';
  $prefix .= t('These settings affect the information available in the <a href="!href">OSSAP Stats embed JS</a>.', array('!href' => url('ossap/stats.js'))) . '</p>';
  $form['ossap_stats']['ossap_stats_embed_message_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Activity message count'),
    '#prefix' => $prefix,
    '#weight' => 15,
    '#size' => 6,
    '#maxlength' => 255,
    '#default_value' => variable_get('ossap_stats_embed_message_count', OSSAP_STATS_EMBED_MESSAGE_COUNT_DEFAULT),
    '#description' => t('(Integer) How many recent activity messages to display.'),
  );
}

/**
 * Returns an HTML5 semantic time tag with datetime, title and time ago text.
 *
 * @see http://microformats.org/wiki/abbr-datetime-pattern
 */
function _ossap_stats_time_markup($timestamp) {
  $markup = '';

  if (!empty($timestamp) && is_numeric($timestamp)) {
    $time = format_interval(time() - $timestamp);
    $datetime = strftime('%Y-%m-%d %H:%M:%S%z', $timestamp);
    $title = format_date($timestamp);
    $time_ago = t('@time ago', array('@time' => $time));
    $build = array(
      '#theme' => 'html_tag',
      '#tag' => 'time',
      '#attributes' => array(
        'class' => array(
          'time',
        ),
        'datetime' => $datetime,
        'title' => $title,
      ),
      '#value' => $time_ago,
    );
    $markup = drupal_render($build);
  }

  return $markup;
}
