<?php

/**
 * @file
 * Allows on server to create vsites on another, through the other server's REST api calls.
 */

function ossap_register_menu_alter(&$items) {
  $items['site/register']['page callback'] = 'drupal_get_form';
  $items['site/register']['page arguments'] = array('ossap_register_site_register_form');
  $items['site/register']['path'] = drupal_get_path('module', 'ossap_register');
  $items['site/register']['file'] = 'ossap_register.form.inc';
}
