<?php

/**
 * @file
 * Allows on server to create vsites on another, through the other server's REST api calls.
 */


function ossap_register_menu_alter(&$items) {
  $items['site/register']['page arguments'] = array('ossap_register_site_register_form');
  $items['site/register']['file path'] = drupal_get_path('module', 'ossap_register');
  $items['site/register']['file'] = 'ossap_register.form.inc';
  $items['site/register']['access callback'] = TRUE;
}

/**
 * Create a vsite via REST
 *
 * @param string $name
 * @param string $purl
 * @param uid $author
 * @param string $bundle
 * @param string $preset
 * @param int $parent
 * @param int $visibility
 */
function ossap_create_vsite($domain ,$name, $purl, $author, $bundle, $preset, $parent, $visibility){

  $new_site = array(
    'body'      => array(LANGUAGE_NONE => array(array())),
    'title'     => $name,
    'type'			=> $bundle,
    'promote'   => 0,
    'revision'  => 1,
    'log'       => '',
    'status'    => 1,
    'sticky'    => 0,
    'language'  => LANGUAGE_NONE,
    'author'    => $author,
    'spaces_preset_og' => $preset,
    'purl' 			=> array(
								    'value' => $purl,
								    'provider'=>'vsite_og',
								    'id'=>NULL,
							     ),
  );

  // Sets the parent relationship if this is a subsite with a parent specified.
  if (isset($parent) && $parent) {
    $new_site['field_group_parent'] = array(LANGUAGE_NONE => array(array(
      'target_id' => $parent,
      'access' => TRUE,
    )));
  }

  // Sets the site visibility value if the module is available and specified.
  if (module_exists('vsite_access')) {
	  if (isset($visibility)) {
	    $new_site[VSITE_ACCESS_FIELD] = $visibility;
	  }
  }

  $servers = variable_get('ossap_child_domains', array());
  if(isset($servers[$domain]['restuser'])){
    $rest_auth = $servers[$domain]['restuser'];
  }else{
    error_log("Unable to find authentication information for domain [{$domain}]");
    $rest_auth = "";
  }

  module_load_include('inc', 'ossap_register', 'includes/ossap_resthelper');
  $json = drupal_json_encode($new_site);
  $result = ossap_httpRequest("http://{$domain}/node", 'POST', $rest_auth, $json);
  $vsite = drupal_json_decode($result);

  return (object) $vsite;
}

/**
 * Create a User via REST api call
 * @param unknown_type $user_options
 */
function ossap_user_create($domain, $user_options){
  $servers = variable_get('ossap_child_domains', array());
  if(isset($servers[$domain]['restuser'])){
    $rest_auth = $servers[$domain]['restuser'];
  }else{
    error_log("Unable to find authentication information for domain [{$domain}]");
    $rest_auth = "";
  }

  module_load_include('inc', 'ossap_register', 'includes/ossap_resthelper');
  $json = drupal_json_encode($user_options);
  $result = ossap_httpRequest("http://{$domain}/user", 'POST', $rest_auth, $json);
  $user = drupal_json_decode($result);

  return (object) $user;
}

/**
 * Checks if a user with these credentials exists
 */
function ossap_user_exists($domain, $username) {

  $servers = variable_get('ossap_child_domains', array());
  if (isset($servers[$domain]['restuser'])){
    $rest_auth = $servers[$domain]['restuser'];
  }
  else {
    error_log("Unable to find authentication information for domain [{$domain}]");
    $rest_auth = "";
  }


  module_load_include('inc', 'ossap_register', 'includes/ossap_resthelper');
  $result = ossap_httpRequest("http://$domain/site/user/exists/$username", 'GET', $rest_auth);
  $data = drupal_json_decode($result);

  return $data['uid'];
}